#!/bin/bash -x

LOG_SUFFIX=$(date +%Y%m%d_%H%M%S)
WRAP_ACCESS_LOG=${VSLBOT_ACCESS_LOG}.app.${LOG_SUFFIX}
WRAP_ERROR_LOG=${VSLBOT_ERROR_LOG}.app.${LOG_SUFFIX}

./wrap-gunicorn.sh 2>${WRAP_ERROR_LOG} >${WRAP_ACCESS_LOG}

